name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      run: |
        go test -v ./...
